CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    deleted      BOOLEAN DEFAULT FALSE                   NOT NULL,
    version      BIGINT  DEFAULT 0                       NOT NULL,
    first_name   VARCHAR(100)                            NOT NULL,
    last_name    VARCHAR(100)                            NOT NULL,
    sex          BOOLEAN                                 NOT NULL,
    birth_date   date                                    NOT NULL,
    phone_number VARCHAR(30)                             NOT NULL,
    address      VARCHAR(300),
    avatar       VARCHAR(100),
    user_name    VARCHAR(100)                            NOT NULL,
    email        VARCHAR(200)                            NOT NULL,
    password     VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);